
export default EventsData = [
    {
        id: 1,
        Ename: 'Event 1',
        Edate: '2024-02-16',
        Etime: '10.00 AM',
        EventImg: 'event1.jpg',
        isRegisteropen: true,
        EventConatct1: 'contact1@example.com',
        EventConatct2: 'contact2@example.com',
        EventSpeaker: 'Speaker Name',
        EventLocation: 'Location A',
        EventTrack: 'Track A',
        EventDest: 'Event description 1',
        isFutureEvent: false,
        formLink: 'https://docs.google.com/forms/d/e/YOUR_FORM_ID1/viewform',
    },
    {
        id: 2,
        Ename: 'Event 2',
        Edate: '2024-02-17',
        Etime: '10.00 AM',
        EventImg: 'event2.jpg',
        isRegisteropen: false,
        EventConatct1: 'contact3@example.com',
        EventConatct2: 'contact4@example.com',
        EventSpeaker: 'Speaker Name 2',
        EventLocation: 'Location B',
        EventTrack: 'Track B',
        EventDest: 'Event description 2',
        isFutureEvent: true,
        formLink: 'https://docs.google.com/forms/d/e/YOUR_FORM_ID2/viewform',
    },
    {
        id: 3,
        Ename: 'Event 3',
        Edate: '2024-02-18',
        Etime: '10.00 AM',
        EventImg: 'event2.jpg',
        isRegisteropen: false,
        EventConatct1: 'contact3@example.com',
        EventConatct2: 'contact4@example.com',
        EventSpeaker: 'Speaker Name 2',
        EventLocation: 'Location B',
        EventTrack: 'Track B',
        EventDest: 'Event description 2',
        isFutureEvent: true,
        formLink: 'https://docs.google.com/forms/d/e/YOUR_FORM_ID2/viewform',
    },
    {
        id: 4,
        Ename: 'Event 4',
        Edate: '2024-02-20',
        Etime: '10.00 AM',
        EventImg: 'event3.jpg',
        isRegisteropen: false,
        EventConatct1: 'contact3@example.com',
        EventConatct2: 'contact4@example.com',
        EventSpeaker: 'Speaker Name 2',
        EventLocation: 'Location B',
        EventTrack: 'Track B',
        EventDest: 'Event description 2',
        isFutureEvent: true,
        formLink: 'https://docs.google.com/forms/d/e/YOUR_FORM_ID2/viewform',
    },
];
